import type { JSX } from "solid-js";
import { createXelComponent } from "./createXelComponent";
import type { XelComponentProps } from "./types";

import "xel/elements/x-accordion.js";
import "xel/elements/x-avatar.js";
import "xel/elements/x-backdrop.js";
import "xel/elements/x-box.js";
import "xel/elements/x-button.js";
import "xel/elements/x-buttons.js";
import "xel/elements/x-card.js";
import "xel/elements/x-checkbox.js";
import "xel/elements/x-colorinput.js";
import "xel/elements/x-colorpicker/x-colorpicker.js";
import "xel/elements/x-colorselect.js";
import "xel/elements/x-contextmenu.js";
import "xel/elements/x-doctab.js";
import "xel/elements/x-doctabs.js";
import "xel/elements/x-drawer.js";
import "xel/elements/x-icon.js";
import "xel/elements/x-input.js";
import "xel/elements/x-label.js";
import "xel/elements/x-menu.js";
import "xel/elements/x-menubar.js";
import "xel/elements/x-menuitem.js";
import "xel/elements/x-message.js";
import "xel/elements/x-nav.js";
import "xel/elements/x-navitem.js";
import "xel/elements/x-notification.js";
import "xel/elements/x-numberinput.js";
import "xel/elements/x-pager.js";
import "xel/elements/x-popover.js";
import "xel/elements/x-progressbar.js";
import "xel/elements/x-radio.js";
import "xel/elements/x-radios.js";
import "xel/elements/x-select.js";
import "xel/elements/x-shortcut.js";
import "xel/elements/x-slider.js";
import "xel/elements/x-stepper.js";
import "xel/elements/x-swatch.js";
import "xel/elements/x-switch.js";
import "xel/elements/x-tab.js";
import "xel/elements/x-tabs.js";
import "xel/elements/x-tag.js";
import "xel/elements/x-tags.js";
import "xel/elements/x-tagsinput.js";
import "xel/elements/x-texteditor.js";
import "xel/elements/x-throbber.js";
import "xel/elements/x-titlebar.js";
import "xel/elements/x-tooltip.js";

type Component<TElement extends HTMLElement = HTMLElement> = (
  props: XelComponentProps<TElement>,
) => JSX.Element;

export const XAccordion: Component = createXelComponent("x-accordion");
export const XAvatar: Component = createXelComponent("x-avatar");
export const XBackdrop: Component = createXelComponent("x-backdrop");
export const XBox: Component = createXelComponent("x-box");
export const XButton: Component = createXelComponent("x-button");
export const XButtons: Component = createXelComponent("x-buttons");
export const XCard: Component = createXelComponent("x-card");
export const XCheckbox: Component = createXelComponent("x-checkbox");
export const XColorInput: Component = createXelComponent("x-colorinput");
export const XColorPicker: Component = createXelComponent("x-colorpicker");
export const XColorSelect: Component = createXelComponent("x-colorselect");
export const XContextMenu: Component = createXelComponent("x-contextmenu");
export const XDocTab: Component = createXelComponent("x-doctab");
export const XDocTabs: Component = createXelComponent("x-doctabs");
export const XDrawer: Component = createXelComponent("x-drawer");
export const XIcon: Component = createXelComponent("x-icon");
export const XInput: Component = createXelComponent("x-input");
export const XLabel: Component = createXelComponent("x-label");
export const XMenu: Component = createXelComponent("x-menu");
export const XMenubar: Component = createXelComponent("x-menubar");
export const XMenuItem: Component = createXelComponent("x-menuitem");
export const XMessage: Component = createXelComponent("x-message");
export const XNav: Component = createXelComponent("x-nav");
export const XNavItem: Component = createXelComponent("x-navitem");
export const XNotification: Component = createXelComponent("x-notification");
export const XNumberInput: Component = createXelComponent("x-numberinput");
export const XPager: Component = createXelComponent("x-pager");
export const XPopover: Component = createXelComponent("x-popover");
export const XProgressbar: Component = createXelComponent("x-progressbar");
export const XRadio: Component = createXelComponent("x-radio");
export const XRadios: Component = createXelComponent("x-radios");
export const XSelect: Component = createXelComponent("x-select");
export const XShortcut: Component = createXelComponent("x-shortcut");
export const XSlider: Component = createXelComponent("x-slider");
export const XStepper: Component = createXelComponent("x-stepper");
export const XSwatch: Component = createXelComponent("x-swatch");
export const XSwitch: Component = createXelComponent("x-switch");
export const XTab: Component = createXelComponent("x-tab");
export const XTabs: Component = createXelComponent("x-tabs");
export const XTag: Component = createXelComponent("x-tag");
export const XTags: Component = createXelComponent("x-tags");
export const XTagsInput: Component = createXelComponent("x-tagsinput");
export const XTextEditor: Component = createXelComponent("x-texteditor");
export const XThrobber: Component = createXelComponent("x-throbber");
export const XTitlebar: Component = createXelComponent("x-titlebar");
export const XTooltip: Component = createXelComponent("x-tooltip");

